import styles from "../styles/Layout.module.css";
import Head from 'next/head'
import Navbar from "./Navbar";


const Layout = ({ children }) => {
  return (
    <div className={styles.layout}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar />
      {children}
    </div>
  );
};

export default Layout;
